sonar.organization=rkristelijn
sonar.projectKey=rkristelijn_muimark
sonar.projectName=muimark

sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx,e2e/**
sonar.exclusions=node_modules/**,.next/**,.tmp/**,data/**,coverage/**

# TypeScript
sonar.typescript.lcov.reportPaths=coverage/lcov.info

# Duplication
sonar.cpd.minimumTokens=60
sonar.cpd.minimumLines=12
